### PR TITLE
addind a dockerfile to demo the build from scratch

### PR DESCRIPTION
**Pull request by dysinger**
This demonstrates Issue #5

### CODE REVIEW

**Comment by dysinger** [comment]
I rebased on `future` and added the opam repo.  It still fails to find all the dependencies.

**Comment by dysinger** [comment]
I had to add a repo and switch to 4.08

**Comment by dysinger** [comment]
This builds and completes successfully now.

**Comment by hannesm** [comment]
@dysinger thanks. do you know of any runes on how to integrate that docker build into the CI used here (travis)? would be great to have a separate job that executes the dockerfile..

**Comment by dysinger** [comment]
I added an arg that will let you change the version of OCAML no the fly but it defaults to 4.08.

like so:
```
for OCAML in 4.06 4.07 4.08 ; do docker build --build-arg=OCAML=${OCAML} --tag mirage-caldav:${OCAML} . ; done
```

**Comment by dysinger** [comment]
I know travis does docker. I haven't done that in a while. I'm sure there are many CIs that do docker will these days.  I'm more focused on Nix/NixOS these days (and curious about Guix and Bazel).

**Pull request closed without merging**
